language: node_js
node_js:
  - 6

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn global add jest

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
